a = int(input("Enter 1st number:"))
b = int(input("Enter 2nd number:"))
c = int(input("Enter 3rd number:"))
d = int(input("Enter 4th number:"))
print("Sum = ",a+b+c+d)
print("product = ",a*b*c*d)
print("Average = ",(a+b+c+d)/4)